version: '3.1'

services:
  db:
    image: postgres:10-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: password01
      TZ: Australia/Sydney
    ports:
      - 5434:5432
      
  ps_schemaupdater:
    build: 
      context: "./personservice"
    environment:
      APPLICATIONNAME: schemaupdater
      db:address: db
      db:username: postgres
      db:password: password01
      db:name: person-service
      db:port: 5432

  ps_api:
    build: 
      context: "./personservice"
    environment:
      APPLICATIONNAME: webapi
      db:address: db
      db:username: postgres
      db:password: password01
      db:name: person-service
      db:port: 5432
    ports:
      - 5000:5000